# Generated by Django 5.1.2 on 2024-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_email_verified",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
