# Generated by Django 5.1.2 on 2024-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_users_is_active_users_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
