# Generated by Django 5.1.2 on 2024-10-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_users_otp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="otp_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
